//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportsman
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Category { get; set; }
        public Nullable<int> Id_state { get; set; }
        public Nullable<int> Id_ivent { get; set; }
        public string Place { get; set; }
        public string photo { get; set; }
    
        public virtual Ivent Ivent { get; set; }
        public virtual State State { get; set; }
    }
}
